image:
  repository: ghcr.io/bryopsida/wireguard
  tag: main
  pullPolicy: Always
podAnnotations: {}
labels: {}
wireguard:
  # -- Address of the VPN server
  serverAddress: 10.34.0.1/24
  #  -- Subnet for your VPN, take care not to clash with cluster POD cidr
  serverCidr: 10.34.0.0/24
  # -- A collection of clients that will be added to wg0.conf, accepts objects with keys PublicKey and AllowedIPs, stored in secret
  clients: []
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: true
  privileged: false
service:
  # -- Whether the service will be created or not
  enabled: true
  # -- Service type, to keep internal to cluster use ClusterIP
  type: NodePort
  # -- Service port, default is 51280 UDP
  port: 51280
# -- Name of a secret with a wireguard private key on key privatekey, if not provided on first install a hook generates one.
secretName: ~
replicaCount: 3
resources:
  requests:
    memory: 256Mi
    cpu: "100m"
  limits:
    memory: 256Mi
    cpu: "100m"
deploymentStrategy:
  type: 'RollingUpdate'
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
disruptionBudget:
  enabled: true
  minAvailable: 2
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
# -- Provide additional environment variables to the wireguard container
extraEnv: {}
#  TEST_ENV_VAR: test-value
# -- If provided, this secret will be used instead of the config created from the helm value scope
configSecretName: ~
# -- The property/key on the secret holding the wireguard configuration file
configSecretProperty: wg0.conf
# -- Disable creation and any mounting of a private key, this assumes another mechanism is provided/used at the container level to fetch the private key
disablePrivateKeyManagement: false
# -- Disable creation and any mount of the wireguard confifugration file, this assumes another mechanism is provided/used to manage a configuration file
disableConfigManagement: false
# -- Passthrough pod volumes
volumes: {}
# -- Passthrough pod volume mounts
volumeMounts: {}
